@startuml
skinparam dpi 300
'skinparam linetype ortho
skinparam shadowing false
top to bottom direction


abstract class Statistic {
  + {abstract} read(data : sacc.Sacc)
  + {final} update_params(params)
  - {abstract} _update_params(params)
  + {abstract} compute(cosmo: pyccl.Cosmology, params: Dict)
}

@enduml
