@startuml

!include skinparams.iuml
!include statistic_frag.iuml
!include updateable_frag.iuml

abstract class Source {}

abstract class UpdateableCollection {}
note bottom
 This will contain only
 <i>Systematic</i> objects.
end note

abstract class TwoPoint {
  - {abstract} _update(params : ParamsDict)
  + {abstract} read(data : sacc.Sacc)
}

TwoPoint -up-|> Updateable
TwoPoint -up-|> Statistic

TwoPoint *--down- Source : s1
TwoPoint *--down- Source : s2
TwoPoint *--down- UpdateableCollection : systematics

class ConcreteTPF {
 - _update(params : ParamsDict)
}
 
ConcreteTPF -left-|> TwoPoint 

@enduml
