@startuml

!include skinparams.iuml

class ParamsDict <<dictionary>> { }
note top
  Map of <i>string</i>
  to <i>float</i>
end note


class Statistics << List[Statistic] >> { }

class SaccData { }
note top
  Represents data read from a sacc.SACC.
  We want to be able to read and write from
  a SACC-format FITS file.
end note

@enduml
