version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_create_environment:
      mamba activate firecrown-docs
      mamba env config vars set CSL_DIR=${CONDA_PREFIX}/cosmosis-standard-library FIRECROWN_DIR=${PWD}
      echo CONDA_PREIX: ${CONDA_PREFIX}
      echo CLS_DIR: ${CSL_DIR}
      echo FIRECROWN_DIR: ${FIRECROWN_DIR}
      mamba activate firecrown-docs  # some day we may need to build the CSL, but not today...

    pre_build:
      - echo $PATH
      - cd tutorial && make
      - mkdir -p docs/_static
      - cp -rf tutorial/*.html tutorial/*.png tutorial/*.jpg docs/_static
