version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_create_environment:
      - conda activate firecrown-docs
      - conda env config vars set CSL_DIR=${CONDA_PREFIX}/cosmosis-standard-library FIRECROWN_DIR=${PWD}
      # some day we may need to build the CSL, but not today...
      - conda activate firecrown-docs && printenv

    pre_build:
      - echo $PATH
      - cd tutorial && make
      - mkdir -p docs/_static
      - cp -rf tutorial/*.html tutorial/*.png tutorial/*.jpg docs/_static
