version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

conda:
  environment: environment.yml

build:
  os: ubuntu-22.04
  tools:
    # Because we are using python: mambaforge-latest, we will be using mamba
    # instead of conda.
    python: mambaforge-latest
  jobs:
    pre_build:
      - echo $PATH
      - mamba info
      - mamba env list
      - mamba activate 499
      - mamba info
      - mamba list
      - which quarto
      - which deno
      # Install firecrown so that we can use it when building the docs.
      - pip install --no-deps --editable .
      - mkdir -p docs/_static
      - wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.42/quarto-1.6.42-linux-amd64.tar.gz && mkdir ~/opt && tar -C ~/opt -xvzf quarto-1.6.42-linux-amd64.tar.gz
      - cd tutorial && PATH="$HOME/opt/quarto-1.6.42/bin:$PATH" quarto render --output-dir=../docs/_static
