version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  apt_packages:
    - plantuml
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - echo $PATH
      - cd docs/diagrams && make 
