version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    # Because we are using python: mambaforge-latest, we will be using mamba
    # instead of conda.
    python: mambaforge-latest
  jobs:
    pre_build:
      - echo $PATH
      # Install firecrown so that we can use it when building the docs.
      - pip install --no-deps --editable .
      - wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.553/quarto-1.4.553-linux-amd64.tar.gz && mkdir ~/opt && tar -C ~/opt -xvzf quarto-1.4.553-linux-amd64.tar.gz
      - cd tutorial && PATH="$HOME/opt/quarto-1.4.553/bin:$PATH" make
      - mkdir -p docs/_static
      - cp -rf tutorial/theoretical_predictions_tutorial.html tutorial/theoretical_predictions_tutorial_files docs/_static
      - cp -rf tutorial/intro_article.html tutorial/intro_article_files docs/_static
      - cp -rf tutorial/introduction_to_firecrown.html tutorial/introduction_to_firecrown_files docs/_static
      - cp -rf tutorial/*.png tutorial/*.jpg docs/_static
