version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

conda:
  environment: environment.yml

build:
  os: ubuntu-22.04
  tools:
    # Because we are using python: mambaforge-latest, we will be using mamba
    # instead of conda.
    python: mambaforge-latest
  jobs:
    pre_build:
      - echo $PATH
      - mamba info
      - mamba env list
      - mamba activate firecrown_developer
      - mamba info
      - mamba list
      - which quarto
      - which deno
      # Install firecrown so that we can use it when building the docs.
      - pip install --no-deps --editable .
      - mkdir -p docs/_static
      - cd tutorial && quarto render --output-dir=../docs/_static
