version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - echo $PATH
      - wget -O quarto_pkg.deb 'https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-1.3.361-linux-amd64.deb' && dpkg -i quarto_pkg.deb
      - cd docs/diagrams && make
      - cd tutorial && make
