# See https://docs.codecov.com/docs/codecovyml-reference for config reference
# To validate: `curl -X POST --data-binary @codecov.yml https://codecov.io/validate`

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: false        
  require_head: true       
  hide_project_coverage: false 

coverage:
  precision: 1
  round: down
  # red below 70, yellow between 70 and 95, green above 95.
  range: 70..95 

  status:
    patch:
      default:
        target: 100%
        threshold: 0%

    project:
      default: 
        target: auto
        threshold: 0%
        removed_code_behavior: fully_covered_patch
      
github_checks:
	annotations: true

