@startuml

!include skinparams.iuml
!include updateable_frag.iuml
!include likelihood_frag.iuml



Updateable <|-down- Likelihood

abstract class ChiSquaredLikelihood {
  +ChiSquaredLikelihood(stats : Statistics)
  +{final} compute_chisq(cosmo : ccl.Cosmology) : double
  - _update(params : ParamsDict)
}

note right of ChiSquaredLikelihood::compute_chisq
  <i>compute_chisq<i> is to be called by derived
  classes in their implementation of <i>compute</i>
end note

note left of ChiSquaredLikelihood::_update
  <i>_update</i> updates <i>systematics</i>
  Classes that override <i>_update</i> should
  make sure to call it as part of their
  implementation, using `super`.
end note


class UpdateableCollection <<Statistic>> {}

ChiSquaredLikelihood *-- UpdateableCollection : systematics

Likelihood <|-down- ChiSquaredLikelihood

class GaussianLikelihood {
  + {final} compute(cosmo : ccl.Cosmology)
}

class StudentTLikelihood {
  + StudentTLikelihood(stats : Statistics, nu : double)
  + {final} compute(cosmo : ccl.Cosmology)
  - _update(params : ParamsDict)
}


ChiSquaredLikelihood <|--down- GaussianLikelihood

ChiSquaredLikelihood <|--down- StudentTLikelihood

@enduml
