@startuml

!include skinparams.iuml
!include updatable_frag.iuml
!include likelihood_frag.iuml



Updatable <|-down- Likelihood

abstract class GaussianFamily {
  +GaussianFamily(stats : Statistics)
  +{final} compute_chisq(cosmo : ccl.Cosmology) : double
  + {final} required_parameters() : RequiredParameters
}

note right of GaussianFamily::compute_chisq
  //compute_chisq// is to be called by derived
  classes in their implementation of //compute//
end note

note left of GaussianFamily::required_parameters
  This call required_parameters() on statistics.
  and then calls required_parameters_gaussian_family()
  and returns the appropriate concatenation.
end note

class UpdatableCollection <<Statistic>> {}

GaussianFamily *-- UpdatableCollection : statistics

Likelihood <|-down- GaussianFamily

class ConstGaussian {
  + {final} compute(cosmo : ccl.Cosmology)
}

class StudentT {
  + StudentT(stats : Statistics, nu : double)
  + {final} compute(cosmo : ccl.Cosmology)
  + {final} required_parameters_gaussian_family() : RequiredParameters
}


GaussianFamily <|--down- ConstGaussian

GaussianFamily <|--down- StudentT

@enduml
