@startuml

!include skinparams.iuml
!include updateable_frag.iuml
!include likelihood_frag.iuml



Updateable <|-down- Likelihood

abstract class GaussianFamily {
  +GaussianFamily(stats : Statistics)
  +{final} compute_chisq(cosmo : ccl.Cosmology) : double
  - _update(params : ParamsDict)
}

note right of GaussianFamily::compute_chisq
  <i>compute_chisq<i> is to be called by derived
  classes in their implementation of <i>compute</i>
end note

note left of GaussianFamily::_update
  <i>_update</i> updates <i>systematics</i>.
  Classes that override <i>_update</i> should
  make sure to call it as part of their
  implementation, using <i>super</i>.
end note


class UpdateableCollection <<Statistic>> {}

GaussianFamily *-- UpdateableCollection : systematics

Likelihood <|-down- GaussianFamily

class ConstGaussian {
  + {final} compute(cosmo : ccl.Cosmology)
}

class StudentT {
  + StudentT(stats : Statistics, nu : double)
  + {final} compute(cosmo : ccl.Cosmology)
  - _update(params : ParamsDict)
}


GaussianFamily <|--down- ConstGaussian

GaussianFamily <|--down- StudentT

@enduml
