@startuml

!include skinparams.iuml
!include updateable_frag.iuml
!include likelihood_frag.iuml

Updateable <|-down- Likelihood

note right of Updateable::_update
  A Likelihood should update its
  state to reflect changes
  //other// than to the cosmology.
end note

note right of Likelihood::read
  //read// is to read both data
  and information about systematics
  from SACC.
end note

note left of Likelihood::compute
  //compute// is to return the
  log likelihood for the contained data,
  given the cosmology //cosmo//.
  It is expected that the state of
  the Likelihood object is not changed
  by this call.
end note


@enduml
