@startuml
!include skinparams.iuml

class SaccData { 
+ add_covariance(cov) : None
+ add_data_point(data_type, tracers, value, tracers_later=False, **tags) : None
+ add_ell_cl(data_type, tracer1, tracer2, ell, x, window=None, tracers_later=False) : None
+ add_theta_xi(data_type, tracer1, tracer2, theta, x, window=None, tracers_later=False) : None
+ add_tracer(tracer_type, name, *args, **kwargs) : None
+ copy() : SaccData
+ get_tracer(name : str) : BaseTracer
+ indices(data_type=None : Optional[str], tracers=None : Optional[Tuple], warn_empty=True, **select) : np.ndarray (int)
+ {static} load_fits(filename) : SaccData
+ mean() : np.ndarray (float)
+ save_fits(filename, overwrite=False) : None
}

note top
  Represents data read from a sacc.SACC.
  We want to be able to read and write from
  a SACC-format FITS file.
end note

note left of SaccData::add_covariance
  To be called after all data points have
  been added.
end note

note left of SaccData::add_data_point
  tags should include angle theta or ell.
end note

note left of SaccData::add_tracer
  Constructs a tracer of the specified type.
  The expected *args and **kwargs depends on
  the type.
end note



@enduml
