@startuml

!include skinparams.iuml
!include updateable_frag.iuml

class UpdateableAtom {
- _update(params : ParamsDict)
}

note top of Updateable
  This design uses the Composite pattern.
end note

note bottom of UpdateableAtom
  This is an example; <i>UpdateableAtom</i> is
  not an actual class; it is
  an example showing a non-collection
  that implements the <i>Updateable</i>
  interface.  
end note

UpdateableAtom -up-|> Updateable

class UpdateableCollection {
  - _update(params : ParamsDict)
  + append(item : Updateable)
}

UpdateableCollection *-- Updateable : contents

note left of UpdateableCollection::_update
  Calls <i>update</i> on each
  item in contents
end note

UpdateableCollection -up-|> Updateable


@enduml
